version: "3.6"

services:
  order_db:
    image: mysql:oracle
    container_name: order_db
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - order_db-volume:/var/lib/mysql
    networks:
      - order-network

networks:
  order-network:
    driver: bridge

volumes:
  order_db-volume:
